allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  "@buxton/auth-google@*": "link:../../Libs/Web/starlex/packages/auth-google"
  "@buxton/core@*": "link:../../Libs/Web/starlex/packages/core"
